// ブロック種別の定義
// ハルクラのすべてのブロック型を管理する

import * as THREE from 'three';

/** ブロックIDの定数定義 */
export const BLOCK_IDS = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  WOOD: 3,
  IRON: 4,
  IRON_CRACKED: 5,
  IRON_MOSSY: 6,
  BEDROCK: 7,
  RAW_WOOD: 8,
  GLASS: 9,
  ENCHANT: 10,
  ELECTRIC: 11,
  SPAWNER: 12,
  STAIRS: 13,
  TORCH: 14,
  BED: 15,
  LEAVES: 16,
  TURRET: 17,
  CORE: 18,
  DOOR: 19,
  LADDER: 20,
  CAMPFIRE: 21,
  CANDLE: 22,
  SNOW: 23,
  SAND: 24,
  RAIL: 25,
  RAIL_SLOPE: 26,
  RAIL_BOOSTER: 27,
  RAIL_LOOP: 28,
  RAIL_CHAIN: 29,
  WATER: 30,
  STONE: 31,
  LAVA: 32,
  COAL_ORE: 33,
  IRON_ORE: 34,
  GOLD_ORE: 35,
  DIAMOND_ORE: 36,
  CHEST: 37,
  FURNACE: 38,
  TNT: 39,
  IRON_INGOT: 40,
  GOLD_INGOT: 41,
  DIAMOND_GEM: 42,
  STICK: 43,
  WHEAT_SEEDS: 44,
  FARMLAND: 45,
  LEVER: 46,
} as const;

export type BlockId = (typeof BLOCK_IDS)[keyof typeof BLOCK_IDS];

/** 面別テクスチャ指定（マイクラ風のブロック用） */
export interface FaceTextures {
  /** 上面テクスチャ */
  top: string;
  /** 側面テクスチャ（前後左右共通） */
  side: string;
  /** 底面テクスチャ */
  bottom: string;
}

/** ブロック情報 */
export interface BlockInfo {
  id: BlockId;
  name: string;
  /** テクスチャファイル名（public/textures/blocks/ 配下） */
  texture: string;
  /** 面別テクスチャ（指定時は texture より優先） */
  faceTextures?: FaceTextures;
  /** 半透明か（ガラス等） */
  transparent: boolean;
  /** 破壊不可か（岩盤） */
  unbreakable: boolean;
  /** 発光するか */
  emissive: boolean;
  /** 発光色（emissive=true の場合） */
  emissiveColor?: THREE.Color;
  /** 発光強度 */
  emissiveIntensity?: number;
  /** ポイントライトの色（光源ブロックの場合） */
  lightColor?: THREE.Color;
  /** ポイントライトの強度 */
  lightIntensity?: number;
  /** ポイントライトの到達距離 */
  lightDistance?: number;
  /** 非標準形状か（松明など、1x1x1ボックスではないもの） */
  nonStandard?: boolean;
  /** 当たり判定がないか（松明のように通過できるもの） */
  noCollision?: boolean;
  /** 液体ブロックか（水・溶岩） */
  isLiquid?: boolean;
  /** 硬さ（破壊にかかる秒数、未指定は0.5） */
  hardness?: number;
  /** 採掘に必要な最低ツールティア（0=素手, 1=木, 2=石, 3=鉄, 4=ダイヤ） */
  minToolTier?: number;
  /** 爆破可能か（TNT） */
  explosive?: boolean;
  /** ブロックカテゴリ（ツール効果判定用: 'stone'|'wood'|'dirt'|'ore'） */
  blockCategory?: string;
}

/** 全ブロックの定義テーブル */
export const BLOCK_DEFS: Record<number, BlockInfo> = {
  [BLOCK_IDS.GRASS]: {
    id: BLOCK_IDS.GRASS,
    name: '草付き土ブロック',
    texture: 'grass.png',
    faceTextures: {
      top: 'grass_top.png',
      side: 'grass_side.png',
      bottom: 'dirt.png',
    },
    transparent: false,
    unbreakable: false,
    emissive: false,
    blockCategory: 'dirt',
  },
  [BLOCK_IDS.DIRT]: {
    id: BLOCK_IDS.DIRT,
    name: '土ブロック',
    texture: 'dirt.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    blockCategory: 'dirt',
  },
  [BLOCK_IDS.WOOD]: {
    id: BLOCK_IDS.WOOD,
    name: '木のブロック',
    texture: 'wood.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    blockCategory: 'wood',
  },
  [BLOCK_IDS.IRON]: {
    id: BLOCK_IDS.IRON,
    name: '鉄ブロック',
    texture: 'iron.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.IRON_CRACKED]: {
    id: BLOCK_IDS.IRON_CRACKED,
    name: 'ひびが入った鉄ブロック',
    texture: 'iron_cracked.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.IRON_MOSSY]: {
    id: BLOCK_IDS.IRON_MOSSY,
    name: 'カビが生えた鉄ブロック',
    texture: 'iron_mossy.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.BEDROCK]: {
    id: BLOCK_IDS.BEDROCK,
    name: '岩盤ブロック',
    texture: 'bedrock.png',
    transparent: false,
    unbreakable: true,
    emissive: false,
  },
  [BLOCK_IDS.RAW_WOOD]: {
    id: BLOCK_IDS.RAW_WOOD,
    name: '生の木ブロック',
    texture: 'raw_wood.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.GLASS]: {
    id: BLOCK_IDS.GLASS,
    name: 'ガラスブロック',
    texture: 'glass.png',
    transparent: true,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.ENCHANT]: {
    id: BLOCK_IDS.ENCHANT,
    name: 'エンチャントブロック',
    texture: 'enchant.png',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0x6633cc),
    emissiveIntensity: 0.6,
    lightColor: new THREE.Color(0x8844ff),
    lightIntensity: 1.5,
    lightDistance: 12,
  },
  [BLOCK_IDS.ELECTRIC]: {
    id: BLOCK_IDS.ELECTRIC,
    name: '電気のブロック',
    texture: 'electric.png',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0x00ddff),
    emissiveIntensity: 1.0,
    lightColor: new THREE.Color(0x44eeff),
    lightIntensity: 3.0,
    lightDistance: 18,
  },
  [BLOCK_IDS.SPAWNER]: {
    id: BLOCK_IDS.SPAWNER,
    name: 'アイアンゴーレムが無限に出てくるブロック',
    texture: 'spawner.png',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xff4422),
    emissiveIntensity: 0.5,
    lightColor: new THREE.Color(0xff6633),
    lightIntensity: 1.0,
    lightDistance: 8,
  },
  [BLOCK_IDS.STAIRS]: {
    id: BLOCK_IDS.STAIRS,
    name: '階段',
    texture: 'stairs.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.TORCH]: {
    id: BLOCK_IDS.TORCH,
    name: '松明',
    texture: 'torch.png',
    transparent: true,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xff8833),
    emissiveIntensity: 1.0,
    lightColor: new THREE.Color(0xffaa44),
    lightIntensity: 2.5,
    lightDistance: 15,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.BED]: {
    id: BLOCK_IDS.BED,
    name: 'ベッド',
    texture: 'bed.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.LEAVES]: {
    id: BLOCK_IDS.LEAVES,
    name: '葉っぱブロック',
    texture: 'leaves.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.TURRET]: {
    id: BLOCK_IDS.TURRET,
    name: '固定タレット',
    texture: 'turret.svg',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xff4444),
    emissiveIntensity: 0.3,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.CORE]: {
    id: BLOCK_IDS.CORE,
    name: '防衛クリスタル',
    texture: 'enchant.png',
    transparent: false,
    unbreakable: true, // プレイヤーからは破壊不可。敵の攻撃とシステムでのみ破壊可能
    emissive: true,
    emissiveColor: new THREE.Color(0x00ffaa),
    emissiveIntensity: 1.5,
    lightColor: new THREE.Color(0x88ffcc),
    lightIntensity: 3.0,
    lightDistance: 20,
  },
  [BLOCK_IDS.DOOR]: {
    id: BLOCK_IDS.DOOR,
    name: 'ドア',
    texture: 'door.svg',
    transparent: false,
    unbreakable: false,
    emissive: false,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.LADDER]: {
    id: BLOCK_IDS.LADDER,
    name: 'ハシゴ',
    texture: 'ladder.svg',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0x4f34ff),
    emissiveIntensity: 0.18,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.CAMPFIRE]: {
    id: BLOCK_IDS.CAMPFIRE,
    name: '焚き火',
    texture: 'campfire.svg',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xff5522),
    emissiveIntensity: 1.2,
    lightColor: new THREE.Color(0xff8a44),
    lightIntensity: 2.8,
    lightDistance: 16,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.CANDLE]: {
    id: BLOCK_IDS.CANDLE,
    name: '蝋燭',
    texture: 'candle.svg',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xffb199),
    emissiveIntensity: 0.8,
    lightColor: new THREE.Color(0xffcaa0),
    lightIntensity: 1.4,
    lightDistance: 9,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.SNOW]: {
    id: BLOCK_IDS.SNOW,
    name: '雪ブロック',
    texture: 'snow.png',
    faceTextures: {
      top: 'snow_top.png',
      side: 'snow_side.png',
      bottom: 'dirt.png',
    },
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.SAND]: {
    id: BLOCK_IDS.SAND,
    name: '砂ブロック',
    texture: 'sand.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.RAIL]: {
    id: BLOCK_IDS.RAIL,
    name: 'レール',
    texture: 'rail.svg',
    transparent: false,
    unbreakable: false,
    emissive: false,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.RAIL_SLOPE]: {
    id: BLOCK_IDS.RAIL_SLOPE,
    name: '坂道レール',
    texture: 'rail_slope.svg',
    transparent: false,
    unbreakable: false,
    emissive: false,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.RAIL_BOOSTER]: {
    id: BLOCK_IDS.RAIL_BOOSTER,
    name: 'ブースターレール',
    texture: 'rail_booster.svg',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xff4400),
    emissiveIntensity: 0.8,
    lightColor: new THREE.Color(0xff6622),
    lightIntensity: 1.2,
    lightDistance: 6,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.RAIL_LOOP]: {
    id: BLOCK_IDS.RAIL_LOOP,
    name: 'ループレール',
    texture: 'rail_loop.svg',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0x8844ff),
    emissiveIntensity: 0.5,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.RAIL_CHAIN]: {
    id: BLOCK_IDS.RAIL_CHAIN,
    name: 'チェーンリフト',
    texture: 'rail_chain.svg',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xcc8800),
    emissiveIntensity: 0.6,
    lightColor: new THREE.Color(0xddaa22),
    lightIntensity: 0.8,
    lightDistance: 5,
    nonStandard: true,
    noCollision: true,
  },
  [BLOCK_IDS.WATER]: {
    id: BLOCK_IDS.WATER,
    name: '水',
    texture: 'water.png',
    transparent: true,
    unbreakable: false,
    emissive: false,
    nonStandard: false,
    noCollision: true,
    isLiquid: true,
  },
  [BLOCK_IDS.STONE]: {
    id: BLOCK_IDS.STONE,
    name: '石ブロック',
    texture: 'stone.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 1.5,
    minToolTier: 1,
    blockCategory: 'stone',
  },
  [BLOCK_IDS.LAVA]: {
    id: BLOCK_IDS.LAVA,
    name: '溶岩',
    texture: 'lava.png',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xff4400),
    emissiveIntensity: 1.5,
    lightColor: new THREE.Color(0xff6622),
    lightIntensity: 3.5,
    lightDistance: 15,
    nonStandard: false,
    noCollision: true,
    isLiquid: true,
  },
  [BLOCK_IDS.COAL_ORE]: {
    id: BLOCK_IDS.COAL_ORE,
    name: '石炭鉱石',
    texture: 'coal_ore.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 3,
    minToolTier: 1,
    blockCategory: 'ore',
  },
  [BLOCK_IDS.IRON_ORE]: {
    id: BLOCK_IDS.IRON_ORE,
    name: '鉄鉱石',
    texture: 'iron_ore.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 4,
    minToolTier: 2,
    blockCategory: 'ore',
  },
  [BLOCK_IDS.GOLD_ORE]: {
    id: BLOCK_IDS.GOLD_ORE,
    name: '金鉱石',
    texture: 'gold_ore.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 5,
    minToolTier: 3,
    blockCategory: 'ore',
  },
  [BLOCK_IDS.DIAMOND_ORE]: {
    id: BLOCK_IDS.DIAMOND_ORE,
    name: 'ダイヤモンド鉱石',
    texture: 'diamond_ore.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 6,
    minToolTier: 3,
    blockCategory: 'ore',
  },
  [BLOCK_IDS.CHEST]: {
    id: BLOCK_IDS.CHEST,
    name: 'チェスト',
    texture: 'chest.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 2,
  },
  [BLOCK_IDS.FURNACE]: {
    id: BLOCK_IDS.FURNACE,
    name: 'かまど',
    texture: 'furnace.png',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0xff6600),
    emissiveIntensity: 0.3,
    hardness: 3,
    minToolTier: 1,
  },
  [BLOCK_IDS.TNT]: {
    id: BLOCK_IDS.TNT,
    name: 'TNT',
    texture: 'tnt.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 0,
    explosive: true,
  },
  [BLOCK_IDS.IRON_INGOT]: {
    id: BLOCK_IDS.IRON_INGOT,
    name: '鉄インゴット',
    texture: 'iron_ingot.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.GOLD_INGOT]: {
    id: BLOCK_IDS.GOLD_INGOT,
    name: '金インゴット',
    texture: 'gold_ingot.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.DIAMOND_GEM]: {
    id: BLOCK_IDS.DIAMOND_GEM,
    name: 'ダイヤモンド',
    texture: 'diamond_gem.png',
    transparent: false,
    unbreakable: false,
    emissive: true,
    emissiveColor: new THREE.Color(0x00ced1),
    emissiveIntensity: 0.3,
  },
  [BLOCK_IDS.STICK]: {
    id: BLOCK_IDS.STICK,
    name: '棒',
    texture: 'stick.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
  },
  [BLOCK_IDS.WHEAT_SEEDS]: {
    id: BLOCK_IDS.WHEAT_SEEDS,
    name: '小麦の種',
    texture: 'grass_top.png',
    transparent: true,
    unbreakable: false,
    emissive: false,
    hardness: 0,
    noCollision: true,
    nonStandard: true,
  },
  [BLOCK_IDS.FARMLAND]: {
    id: BLOCK_IDS.FARMLAND,
    name: '耕地',
    texture: 'dirt.png',
    transparent: false,
    unbreakable: false,
    emissive: false,
    hardness: 0.3,
    blockCategory: 'dirt',
  },
  [BLOCK_IDS.LEVER]: {
    id: BLOCK_IDS.LEVER,
    name: 'レバー',
    texture: 'stone.png',
    transparent: true,
    unbreakable: false,
    emissive: false,
    hardness: 0,
    noCollision: true,
    nonStandard: true,
  },
};

/** ホットバーに並ぶブロックの順番 */
export const HOTBAR_BLOCKS: BlockId[] = [
  BLOCK_IDS.GRASS,
  BLOCK_IDS.DIRT,
  BLOCK_IDS.WOOD,
  BLOCK_IDS.RAW_WOOD,
  BLOCK_IDS.IRON,
  BLOCK_IDS.GLASS,
  BLOCK_IDS.ENCHANT,
  BLOCK_IDS.ELECTRIC,
  BLOCK_IDS.SPAWNER,
  BLOCK_IDS.TURRET,
  BLOCK_IDS.CORE,
  BLOCK_IDS.RAIL,
  BLOCK_IDS.RAIL_SLOPE,
  BLOCK_IDS.RAIL_BOOSTER,
  BLOCK_IDS.RAIL_LOOP,
  BLOCK_IDS.RAIL_CHAIN,
  BLOCK_IDS.CHEST,
  BLOCK_IDS.FURNACE,
  BLOCK_IDS.TNT,
  BLOCK_IDS.STONE,
  BLOCK_IDS.SAND,
  BLOCK_IDS.WATER,
  BLOCK_IDS.LAVA,
];

/** チャンクサイズ定数 */
export const CHUNK_SIZE = 16;
/** ワールドの高さ限界 */
export const WORLD_HEIGHT = 128;
/** 海面レベル（この高さ以下の空気ブロックが水で埋まる） */
export const SEA_LEVEL = 16;
/** 初期のレンダリング距離（チャンク数） — 広大なバイオームワールド */
export const RENDER_DISTANCE = 12;
